package util;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

/**
 * Minimal .xlsx reader using only the JDK (java.util.zip + javax.xml).
 * No Apache POI / external jars required.
 *
 * Reads the FIRST worksheet into a row/column grid of trimmed strings.
 * Handles both inline strings (t="inlineStr"), shared strings (t="s"),
 * plain string cells (t="str") and numeric cells.
 *
 * Scope is intentionally narrow: it is enough to parse the attendance
 * import templates generated by attendance-templates/generate_templates.py
 * and the same files re-saved by Excel / WPS / Google Sheets.
 */
public final class XlsxReader {

    /** A parsed sheet: cells[row][col], 0-based, null where empty. */
    public static final class Sheet {
        private final List<List<String>> rows;
        Sheet(List<List<String>> rows) { this.rows = rows; }

        /** Number of rows that contain at least one cell. */
        public int rowCount() { return rows.size(); }

        /** Cell value at 0-based (row, col); "" if missing. Never null. */
        public String get(int row, int col) {
            if (row < 0 || row >= rows.size()) return "";
            List<String> r = rows.get(row);
            if (col < 0 || col >= r.size()) return "";
            String v = r.get(col);
            return v == null ? "" : v;
        }

        /** Max column index used in a given row (exclusive bound). */
        public int colCount(int row) {
            if (row < 0 || row >= rows.size()) return 0;
            return rows.get(row).size();
        }
    }

    private XlsxReader() {}

    /** Parse the first worksheet of an .xlsx stream. */
    public static Sheet readFirstSheet(InputStream xlsx) throws IOException {
        Map<String, byte[]> entries = new HashMap<>();
        try (ZipInputStream zis = new ZipInputStream(xlsx)) {
            ZipEntry e;
            byte[] buf = new byte[8192];
            while ((e = zis.getNextEntry()) != null) {
                if (e.isDirectory()) continue;
                java.io.ByteArrayOutputStream bos = new java.io.ByteArrayOutputStream();
                int n;
                while ((n = zis.read(buf)) != -1) bos.write(buf, 0, n);
                entries.put(e.getName(), bos.toByteArray());
            }
        }

        List<String> shared = readSharedStrings(entries.get("xl/sharedStrings.xml"));

        String sheetPath = resolveFirstSheetPath(entries);
        byte[] sheetBytes = entries.get(sheetPath);
        if (sheetBytes == null) {
            throw new IOException("Worksheet not found in workbook: " + sheetPath);
        }
        return parseSheet(sheetBytes, shared);
    }

    /** Locate the first worksheet part; falls back to the conventional path. */
    private static String resolveFirstSheetPath(Map<String, byte[]> entries) {
        // Default layout produced by openpyxl / Excel.
        if (entries.containsKey("xl/worksheets/sheet1.xml")) {
            return "xl/worksheets/sheet1.xml";
        }
        // Otherwise pick the lowest-numbered worksheet present.
        String best = null;
        for (String name : entries.keySet()) {
            if (name.startsWith("xl/worksheets/") && name.endsWith(".xml")) {
                if (best == null || name.compareTo(best) < 0) best = name;
            }
        }
        return best != null ? best : "xl/worksheets/sheet1.xml";
    }

    private static List<String> readSharedStrings(byte[] xml) throws IOException {
        List<String> out = new ArrayList<>();
        if (xml == null) return out;
        Document doc = parse(xml);
        NodeList siList = doc.getElementsByTagName("si");
        for (int i = 0; i < siList.getLength(); i++) {
            out.add(concatText((Element) siList.item(i)));
        }
        return out;
    }

    /** Concatenate all <t> descendants (handles rich text runs). */
    private static String concatText(Element parent) {
        StringBuilder sb = new StringBuilder();
        NodeList tList = parent.getElementsByTagName("t");
        for (int i = 0; i < tList.getLength(); i++) {
            sb.append(tList.item(i).getTextContent());
        }
        return sb.toString();
    }

    private static Sheet parseSheet(byte[] xml, List<String> shared) throws IOException {
        Document doc = parse(xml);
        List<List<String>> rows = new ArrayList<>();

        NodeList rowList = doc.getElementsByTagName("row");
        for (int i = 0; i < rowList.getLength(); i++) {
            Element rowEl = (Element) rowList.item(i);
            int rowIdx = parseInt(rowEl.getAttribute("r"), i + 1) - 1; // 1-based -> 0-based
            while (rows.size() <= rowIdx) rows.add(new ArrayList<>());
            List<String> cells = rows.get(rowIdx);

            NodeList cList = rowEl.getElementsByTagName("c");
            for (int j = 0; j < cList.getLength(); j++) {
                Element c = (Element) cList.item(j);
                int colIdx = colFromRef(c.getAttribute("r"), j);
                String value = readCellValue(c, shared);
                while (cells.size() <= colIdx) cells.add(null);
                cells.set(colIdx, value == null ? null : value.trim());
            }
        }
        return new Sheet(rows);
    }

    private static String readCellValue(Element c, List<String> shared) {
        String t = c.getAttribute("t"); // "s","inlineStr","str","b","e", or "" (number)

        if ("inlineStr".equals(t)) {
            NodeList isList = c.getElementsByTagName("is");
            if (isList.getLength() > 0) return concatText((Element) isList.item(0));
            return "";
        }

        // Shared / plain string / number all expose the payload in <v>.
        String raw = firstChildText(c, "v");
        if (raw == null) return "";

        if ("s".equals(t)) {
            int idx = parseInt(raw, -1);
            if (idx >= 0 && idx < shared.size()) return shared.get(idx);
            return "";
        }
        // "str" (formula result), number, boolean -> raw text as-is.
        return raw;
    }

    private static String firstChildText(Element parent, String tag) {
        NodeList nl = parent.getElementsByTagName(tag);
        if (nl.getLength() == 0) return null;
        // Only count direct <v>, not nested ones from other namespaces.
        for (int i = 0; i < nl.getLength(); i++) {
            Node n = nl.item(i);
            if (n.getParentNode() == parent) return n.getTextContent();
        }
        return nl.item(0).getTextContent();
    }

    /** Column index (0-based) from a cell ref like "AB12"; fallback to seq. */
    static int colFromRef(String ref, int fallback) {
        if (ref == null || ref.isEmpty()) return fallback;
        int col = 0;
        boolean any = false;
        for (int i = 0; i < ref.length(); i++) {
            char ch = ref.charAt(i);
            if (ch >= 'A' && ch <= 'Z') {
                col = col * 26 + (ch - 'A' + 1);
                any = true;
            } else if (ch >= 'a' && ch <= 'z') {
                col = col * 26 + (ch - 'a' + 1);
                any = true;
            } else {
                break; // reached the row number
            }
        }
        return any ? col - 1 : fallback;
    }

    private static int parseInt(String s, int dflt) {
        try { return Integer.parseInt(s.trim()); }
        catch (Exception ex) { return dflt; }
    }

    private static Document parse(byte[] xml) throws IOException {
        try {
            DocumentBuilderFactory f = DocumentBuilderFactory.newInstance();
            f.setNamespaceAware(false);
            // Harden against XXE — these files are user uploads.
            f.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
            f.setExpandEntityReferences(false);
            DocumentBuilder b = f.newDocumentBuilder();
            return b.parse(new ByteArrayInputStream(xml));
        } catch (IOException ioe) {
            throw ioe;
        } catch (Exception ex) {
            throw new IOException("Failed to parse worksheet XML: " + ex.getMessage(), ex);
        }
    }
}
